server:
  servlet:
    context-path: /api
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    removeAbandoned: true
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
